### ISSUE TITLE
core scripts

### ISSUE THREAD

**Issue by garciagenrique** [cta-observatory/lstmcpipe#147]
trying to run a `lstmcpipe_lst_core_r0_dl1` standalone, the script returns this error

@LukasNickel could you recall me please why we are using this variable ?

```
$ lstmcpipe_lst_core_r0_dl1 -c /fefs/home/enrique.garcia/software/lstmcpipe/lstmcpipe/lstchain_standard_config_v082_MC_Tel1.json  -f /fefs/aswg/workspace/enrique.garcia/workflow_r0_dl2_lst/running_analysis/20200629_prod5_trans_80/electron/zenith_20deg/south_pointing/20220114_v0.8.4_prod5_trans_80_test_v084_test_merge/file_lists_training/training_0.list --output_dir /fefs/aswg/workspace/enrique.garcia/workflow_r0_dl2_lst/running_analysis/20200629_prod5_trans_80/electron/zenith_20deg/south_pointing/20220114_v0.8.4_prod5_trans_80_test_v084_test_merge/DL1/training
Traceback (most recent call last):
  File "/fefs/aswg/software/conda/envs/lstchain-v0.8.4/bin/lstmcpipe_lst_core_r0_dl1", line 8, in <module>
    sys.exit(main())
  File "/home/enrique.garcia/.local/lib/python3.8/site-packages/lstmcpipe/scripts/script_batch_filelist_lst.py", line 40, in main
    task_id = int(environ["SLURM_ARRAY_TASK_ID"])
  File "/fefs/aswg/software/conda/envs/lstchain-v0.8.4/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'SLURM_ARRAY_TASK_ID'
(lstchain-v0.8.4) enrique.garcia@cp01 job_logs $ ipython
import Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.0.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import os

In [2]: from os import environ

In [3]: environ["SLURM_ARRAY_TASK_ID"]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [3], in <module>
----> 1 environ["SLURM_ARRAY_TASK_ID"]

File /fefs/aswg/software/conda/envs/lstchain-v0.8.4/lib/python3.8/os.py:675, in _Environ.__getitem__(self, key)
    672     value = self._data[self.encodekey(key)]
    673 except KeyError:
    674     # raise KeyError with the original key value
--> 675     raise KeyError(key) from None
    676 return self.decodevalue(value)

KeyError: 'SLURM_ARRAY_TASK_ID'

```

**Comment by LukasNickel** [comment]
To run the r0 dl1 step in a slurm job array.
It tells the script which file to choose for the list of r0 files.

**Comment by garciagenrique** [comment]
Thanks @LukasNickel, this will need to be improved, we cannot launch core scripts individually. I can take care of it.
