### ISSUE TITLE
prod `v0.10.4_prod5_trans80` failed

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/lstmcpipe#456]
``` 
cat /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/gamma-diffuse/zenith_20deg/south_pointing/v0.10.4_prod5_trans80/split_tt_33067609.e 
Traceback (most recent call last):
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.4/bin/lstmcpipe_train_test_split", line 11, in <module>
    sys.exit(main())
             ^^^^^^
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.4/lib/python3.11/site-packages/lstmcpipe/scripts/script_train_test_splitting.py", line 86, in main
    train, test = train_test_split(file_list, random_state=42, test_size=float(args.ratio), shuffle=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.4/lib/python3.11/site-packages/sklearn/model_selection/_split.py", line 2562, in train_test_split
    n_train, n_test = _validate_shuffle_split(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.4/lib/python3.11/site-packages/sklearn/model_selection/_split.py", line 2236, in _validate_shuffle_split
    raise ValueError(
ValueError: With n_samples=0, test_size=0.5 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
```

**Comment by vuillaut** [comment]
The issue is actually in the R0 to DL1 stage:

```
cat /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/gamma-diffuse/zenith_20deg/south_pointing/v0.10.4_prod5_trans80/job_logs_r0dl1/job_33067604_0.e  

RuntimeError: `SimTelEventSource.focal_length_choice` was set to 'EFFECTIVE', but the effective focal length was not present in the file. Set `focal_length_choice='EQUIVALENT'` or make sure input files contain the effective focal length
```

**Comment by moralejo** [comment]
This could be fixed by the source, right? - if the telescope is a known one like LST is.

**Comment by vuillaut** [comment]
> This could be fixed by the source, right? - if the telescope is a known one like LST is.

Yes, #460 should fix this.    
I have added a note in the doc as well.
