### ISSUE TITLE
failed merge stage

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/lstmcpipe#491]
```
INFO    |Submitted batch job 39387195
INFO    |==== END batch train_test_splitting ====
INFO    |==== START batch merge_and_copy_dl1_workflow ====
Traceback (most recent call last):
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.12/bin/lstmcpipe", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.12/lib/python3.11/site-packages/lstmcpipe/lstmcpipe_start.py", line 206, in main
    jobs_from_merge = batch_merge_dl1(
                      ^^^^^^^^^^^^^^^^
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.12/lib/python3.11/site-packages/lstmcpipe/stages/mc_merge_dl1.py", line 42, in batch_merge_dl1
    job_logs, jobid_debug = merge_dl1(
                            ^^^^^^^^^^
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.12/lib/python3.11/site-packages/lstmcpipe/stages/mc_merge_dl1.py", line 106, in merge_dl1
    jobid_merge = sbatch_merge_dl1.submit()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.12/lib/python3.11/site-packages/lstmcpipe/utils.py", line 333, in submit
    jobid = run_command(self.slurm_command)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.12/lib/python3.11/site-packages/lstmcpipe/utils.py", line 218, in run_command
    raise ValueError(f"Running `{args[0]}` failed with return code {cmd.returncode}, output: \n {stdout}")
ValueError: Running `sbatch --parsable --partition=long --job-name=merge --account=dpps --error=/fefs/aswg/data/mc/DL1/AllSky/20240909_allsky_nsb_tuning_0.00/TrainingDataset/GammaDiffuse/dec_2276/merging-output_%j.e --output=/fefs/aswg/data/mc/DL1/AllSky/20240909_allsky_nsb_tuning_0.00/TrainingDataset/GammaDiffuse/dec_2276/merging-output_%j.o --dependency=afterok:39385545:39385556:39385569:39385571:39385593:39385594:39385617:39385629:39385641:39385649:39385650:39385651:39385652:39385653:39385654:39385655:39385656:39385657:39385658:39385659:39385660:39385661:39385662:39385663:39385664:39385665:39385666:39385667:39385668:39385669:39385670:39385671:39385672:39385673:39385674:39385675:39385676:39385677:39385678:39385679:39385680:39385681:39385682:39385683:39385684:39385685:39385686:39385687:39385688:39385689:39385690:39385691:39385692:39385693:39385694:39385695:39385696:39385697:39385698:39385699:39385700:39385701:39385702:39385703:39385704:39385705:39385706:39385707:39385708:39385709:39385710:39385711:39385712:39385714:39385715:39385716:39385717:39385718:39385719:39385720:39385721:39385722:39385723:39385724:39385725:39385726:39385727:39385728:39385729:39385730:39385731:39385732:39385733:39385734:39385735:39385736:39385737:39385738:39385739:39385740:39385741:39385742:39385743:39385744:39385745:39385746:39385747:39385748:39385749:39385750:39385751:39385752:39385753:39385754:39385755:39385756:39385757:39385758:39385759:39385760:39385761:39385762:39385763:39385764:39385765:39385766:39385767:39385768:39385770:39385771:39385772:39385773:39385774:39385775:39385776:39385777:39385778:39385779:39385780:39385781:39385782:39385783:39385784:39385785:39385786:39385787:39385788:39385789:39385790:39385791:39385792:39385793:39385794:39385795:39385796:39385797:39385798:39385799:39385800:39385801:39385802:39385803:39385804:39385805:39385806:39385807:39385808:39385809:39385810:39385811:39385812:39385813:39385814:39385815:39385816:39385817:39385818:39385819:39385820:39385821:39385822:39385823:39385824:39385825:39385826:39385827:39385828:39385829:39385830:39385831:39385832:39385833:39385834:39385835:39385836:39385837:39385838:39385871:39385872:39385873:39385874:39385875:39385876:39385877:39385878:39385879:39385912:39385913:39385914:39385915:39385916:39385917:39385918:39385919:39385920:39385921:39385922:39385923:39385924:39385925:39385926:39385927:39385928:39385929:39385930:39385931:39385932:39385933:39385934:39385935:39385936:39385937:39385938:39385939:39385940:39385941:39385942:39385943:39385944:39385945:39385946:39385947:39385948:39385949:39385950:39385951:39385952:39385953:39385954:39385987:39385988:39385989:39385990:39385991:39385992:39385993:39385994:39385995:39385996:39385997:39385998:39385999:39386000:39386001:39386002:39386003:39386004:39386005:39386006:39386007:39386008:39386009:39386010:39386011:39386012:39386013:39386014:39386015:39386016:39386017:39386018:39386019:39386020:39386021:39386022:39386053:39386054:39386055:39386056:39386057:39386058:39386059:39386060:39386061:39386062:39386063:39386064:39386065:39386066:39386067:39386068:39386069:39386070:39386071:39386072:39386073:39386074:39386075:39386076:39386077:39386078:39386079:39386080:39386081:39386082:39386083:39386084:39386085:39386086:39386087:39386088:39386089:39386090:39386091:39386092:39386093:39386094:39386095:39386099:39386102:39386103:39386104:39386105:39386110:39386111:39386112:39386113:39386115:39386116:39386117:39386119:39386121:39386122:39386126:39386129:39386130:39386138:39386139:39386140:39386142:39386143:39386147:39386149:39386160:39386161:39386162:39386177:39386181:39386182:39386183:39386185:39386200:39386201:39386202:39386203:39386205:39386206:39386208:39386213:39386214:39386216:39386217:39386219:39386224:39386225:39386226:39386227:39386230:39386231:39386245:39386246:39386247:39386248:39386250:39386258:39386262:39386264:39386266:39386267:39386270:39386271:39386272:39386273:39386274:39386275:39386276:39386277:39386278:39386283:39386285:39386286:39386287:39386288:39386289:39386293:39386294:39386296:39386297:39386299:39386301:39386306:39386307:39386308:39386310:39386318:39386321:39386324:39386325:39386331:39386337:39386345:39386350:39386358:39386365:39386372:39386387:39386390:39386391:39386393:39386397:39386402:39386403:39386404:39386414:39386418:39386422:39386434:39386438:39386445:39386456:39386461:39386465:39386467:39386470:39386472:39386475:39386478:39386480:39386483:39386484:39386488:39386491:39386495:39386499:39386508:39386510:39386517:39386535:39386542:39386558:39386563:39386578:39386579:39386585:39386590:39386592:39386594:39386595:39386596:39386599:39386600:39386602:39386609:39386611:39386615:39386623:39386627:39386629:39386631:39386633:39386634:39386637:39386647:39386648:39386649:39386651:39386661:39386662:39386664:39386672:39386680:39386688:39386689:39386692:39386693:39386694:39386699:39386718:39386730:39386732:39386742:39386743:39386744:39386746:39386747:39386751:39386755:39386767:39386770:39386776:39386782:39386790:39386798:39386800:39386804:39386807:39386808:39386809:39386815:39386822:39386824:39386828:39386829:39386830:39386831:39386832:39386833:39386835:39386837:39386838:39386839:39386840:39386842:39386848:39386849:39386850:39386851:39386852:39386853:39386854:39386855:39386856:39386857:39386858:39386859:39386860:39386861:39386862:39386863:39386864:39386865:sbatch: error: Slurm temporarily unable to accept job: sleeping and retrying
39386877:39386878:39386879:39386880:39386881:39386883:39386884:39386885:39386886:39386887:39386888:39386889:39386893:39386897:39386900:39386901:39386902:39386903:39386904:39386905:39386906:39386907:39386908:39386909:39386910:39386911:39386912:39386913:39386914:39386915:sbatch: error: Slurm temporarily unable to accept job: sleeping and retrying
39386932:39386935:39386936:39386938:39386944:39386945:39386946:39386947:39386948:39386949:39386950:39386951:39386952:39386953:39386954:39386957:39386958:39386959:39386960:39386961:39386963:39386964:39386965:39386966:39386967:39386968:39386969:39386970:39386971:39386973:39386974:39386975:39386976:39386977:39386978:39386979:sbatch: error: Slurm temporarily unable to accept job: sleeping and retrying
39387003:39387009:39387010:39387011:39387012:39387013:39387015:39387016:39387017:39387018:39387019:39387020:39387021:39387022:39387023:39387024:39387025:39387026:39387027:39387028:39387029:39387030:39387033:39387034:39387035:39387036:39387037:39387038:39387039:39387040:39387041:39387042:39387045:39387046:39387047:sbatch: error: Slurm temporarily unable to accept job: sleeping and retrying
39387073:39387075:39387077:39387078:39387079:39387080:39387082:39387083:39387084:39387085:39387086:39387087:39387088:39387089:39387090:39387091:39387092:39387093:39387094:39387095:39387096:39387097:39387098:39387099:39387100:39387101:39387102:39387103:39387104:39387105:sbatch: error: Slurm temporarily unable to accept job: sleeping and retrying
39387122:39387123:39387124:39387127:39387133:39387134:39387135:39387136:39387137:39387138:39387139:39387140:39387141:39387142:39387143:39387144:39387145:39387146:39387147:39387148:39387149:39387150:39387151:39387152:39387153:39387154:39387155:39387157:39387160:39387161:39387162:39387163:39387164:39387165:39387166:39387168:39387169:39387170:39387171:sbatch: error: Slurm temporarily unable to accept job: sleeping and retrying
39387185:39387187:39387190:39387191:39387192:39387193:39387194:39387195 --time=06:00:00 --nice=10  --wrap="source /fefs/aswg/software/conda/etc/profile.d/conda.sh; conda activate lstchain-v0.10.12; lstchain_merge_hdf5_files -d /fefs/aswg/data/mc/DL1/AllSky/20240909_allsky_nsb_tuning_0.00/TrainingDataset/GammaDiffuse/dec_2276 -o /fefs/aswg/data/mc/DL1/AllSky/20240909_allsky_nsb_tuning_0.00/TrainingDataset/GammaDiffuse/dec_2276/dl1_20240909_allsky_nsb_tuning_0.00_train_dec_2276_GammaDiffuse_merged.h5 --pattern */*/*.h5 --no-image || exit \$?"` failed with return code 127, output: 
 sbatch: error: Unable to open file error:
/bin/sh: line 1: 39386877:39386878:39386879:39386880:39386881:39386883:39386884:39386885:39386886:39386887:39386888:39386889:39386893:39386897:39386900:39386901:39386902:39386903:39386904:39386905:39386906:39386907:39386908:39386909:39386910:39386911:39386912:39386913:39386914:39386915:sbatch:: command not found
/bin/sh: line 2: 39386932:39386935:39386936:39386938:39386944:39386945:39386946:39386947:39386948:39386949:39386950:39386951:39386952:39386953:39386954:39386957:39386958:39386959:39386960:39386961:39386963:39386964:39386965:39386966:39386967:39386968:39386969:39386970:39386971:39386973:39386974:39386975:39386976:39386977:39386978:39386979:sbatch:: command not found
/bin/sh: line 3: 39387003:39387009:39387010:39387011:39387012:39387013:39387015:39387016:39387017:39387018:39387019:39387020:39387021:39387022:39387023:39387024:39387025:39387026:39387027:39387028:39387029:39387030:39387033:39387034:39387035:39387036:39387037:39387038:39387039:39387040:39387041:39387042:39387045:39387046:39387047:sbatch:: command not found
/bin/sh: line 4: 39387073:39387075:39387077:39387078:39387079:39387080:39387082:39387083:39387084:39387085:39387086:39387087:39387088:39387089:39387090:39387091:39387092:39387093:39387094:39387095:39387096:39387097:39387098:39387099:39387100:39387101:39387102:39387103:39387104:39387105:sbatch:: command not found
/bin/sh: line 5: 39387122:39387123:39387124:39387127:39387133:39387134:39387135:39387136:39387137:39387138:39387139:39387140:39387141:39387142:39387143:39387144:39387145:39387146:39387147:39387148:39387149:39387150:39387151:39387152:39387153:39387154:39387155:39387157:39387160:39387161:39387162:39387163:39387164:39387165:39387166:39387168:39387169:39387170:39387171:sbatch:: command not found
/bin/sh: line 6: 39387185:39387187:39387190:39387191:39387192:39387193:39387194:39387195: command not found
```

**Comment by vuillaut** [comment]
Fixed
